=== egrycs/java-sample/src/main/resources/sampleInvoice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://sample.dto.onboaring.icellmobilsoft.hu/invoice"
           xmlns="http://sample.dto.onboaring.icellmobilsoft.hu/invoice"
           elementFormDefault="qualified">

    <xs:simpleType name="SimpleText50Type">
        <xs:restriction base="xs:string">
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="IdType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="32"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="UnitOfMeasureType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="KG"/>
            <xs:enumeration value="PIECE"/>
            <xs:enumeration value="HOUR"/>
            <xs:enumeration value="CUSTOM"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="DecimalType">
        <xs:restriction base="xs:decimal">
            <xs:totalDigits value="15"/>
            <xs:fractionDigits value="2"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="LineType">
        <xs:sequence>
            <xs:element name="id" type="IdType"/>
            <xs:element name="name" type="SimpleText50Type"/>
            <xs:element name="quantity" type="xs:int"/>
            <xs:element name="unitOfMeasure" type="UnitOfMeasureType"/>
            <xs:element name="customUnitOfMeasure" type="xs:string" minOccurs="0"/>
            <xs:element name="unitPrice" type="DecimalType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LineListType">
        <xs:sequence>
            <xs:element name="line" type="LineType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
	
	<xs:complexType name="InvoiceLineListType">
        <xs:sequence>
            <xs:element name="line" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InvoiceType">
        <xs:sequence>
            <xs:element name="id" type="IdType"/>
            <xs:element name="invoiceNumber" type="SimpleText50Type"/>
            <xs:element name="invoiceType" type="xs:string"/>
            <xs:element name="supplierTaxNumber" type="xs:string"/>
            <xs:element name="customerTaxNumber" type="xs:string" minOccurs="0"/>
            <xs:element name="lines" type="InvoiceLineListType" minOccurs="0"/>
			<xs:element name="sumPrice" type="DecimalType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
	
	<xs:complexType name="InvoiceListType">
        <xs:sequence>
            <xs:element name="invoice" type="InvoiceType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InvoiceDataType">
        <xs:sequence>
            <xs:element name="invoice" type="InvoiceType"/>
            <xs:element name="lines" type="LineListType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="InvoiceDataListType">
        <xs:sequence>
            <xs:element name="invoiceData" type="InvoiceDataType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="sample">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lines" type="LineListType"/>
                <xs:element name="invoices" type="InvoiceListType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== egrycs/java-sample/src/main/resources/pelda.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<sample xmlns="http://sample.dto.onboarding.icellmobilsoft.hu/invoice"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://sample.dto.onboarding.icellmobilsoft.hu/invoice xsd/sampleInvoice.xsd">
    <lines>
        <line>
            <id>000001</id>
            <name>Kristály cukor</name>
            <quantity>5</quantity>
            <unitOfMeasure>KG</unitOfMeasure>
            <unitPrice>259</unitPrice>
        </line>
        <line>
            <id>000002</id>
            <name>Csülök pörkölt</name>
            <quantity>1</quantity>
            <unitOfMeasure>CUSTOM</unitOfMeasure>
            <customUnitOfMeasure>tányér</customUnitOfMeasure>
            <unitPrice>6900</unitPrice>
        </line>
        <line>
            <id>000003</id>
            <name>Irodai szék</name>
            <quantity>19</quantity>
            <unitOfMeasure>PIECE</unitOfMeasure>
            <unitPrice>75890</unitPrice>
        </line>
        <line>
            <id>000004</id>
            <name>Irodai szék duplikáció</name>
            <quantity>19</quantity>
            <unitOfMeasure>PIECE</unitOfMeasure>
            <unitPrice>75890</unitPrice>
        </line>
    </lines>
    <invoices>
        <invoice>
            <id>12345</id>
            <invoiceNumber>ICELL-2023-03</invoiceNumber>
            <invoiceType>NORMAL</invoiceType>
            <supplierTaxNumber>31415926</supplierTaxNumber>
            <customerTaxNumber>32468972</customerTaxNumber>
            <lines>
                <line>000001</line>
                <line>000002</line>
            </lines>
            <sumPrice>8195</sumPrice>
        </invoice>
        <invoice>
            <id>54321</id>
            <invoiceNumber>JAVA2023-03/10</invoiceNumber>
            <invoiceType>NORMAL</invoiceType>
            <supplierTaxNumber>32468972</supplierTaxNumber>
            <customerTaxNumber>31415926</customerTaxNumber>
            <lines>
                <line>000001</line>
                <line>000002</line>
                <line>000003</line>
            </lines>
            <sumPrice>1450105</sumPrice>
        </invoice>
        <invoice>
            <id>32154</id>
            <invoiceNumber>SIMMPLE0002</invoiceNumber>
            <invoiceType>SIMPLE</invoiceType>
            <supplierTaxNumber>31415926</supplierTaxNumber>
            <customerTaxNumber>31415926</customerTaxNumber>
            <sumPrice>100</sumPrice>
        </invoice>
    </invoices>
</sample>
